esphome:
  name: espkyogate
  platform: ESP8266
  board: d1_mini
  includes:
    - bentel_kyo32.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Test Fallback Hotspot"
    password: "12345678"

captive_portal:

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret ha_password

ota:
  password: !secret ota_password

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: EVEN

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return { kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->zona_1,
        kyo32->zona_sabotaggio_1,
        kyo32->allarme_area_1,
        kyo32->inserimento_totale_area_1,
        kyo32->inserimento_parziale_area_1,
        kyo32->memoria_allarme_zona_1,
        kyo32->memoria_sabotaggio_zona_1,
        kyo32->disinserita_area_1,
        kyo32->warn_scomparsa_bpi, kyo32->warn_fusibile, kyo32->warn_batteria_bassa, kyo32->warn_guasto_linea_telefonica, kyo32->warn_codici_default, kyo32->warn_wireless,
        kyo32->sabotaggio_chiave_falsa, kyo32->sabotaggio_bpi, kyo32->sabotaggio_jam, kyo32->sabotaggio_wireless
        };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: zona_1
        name: "Zona 1"
      - id: zona_sabotaggio_1
        name: "Zona 1 Sabotaggio"
      - id: allarme_area_1
        name: "Allarme Area 1"
      - id: inserimento_totale_area_1
        name: "Inserimento Totale Area 1"
      - id: inserimento_parziale_area_1
        name: "Inserimento Parziale Area 1"
      - id: memoria_allarme_zona_1
        name: "Memoria Allarme Zona 1"
      - id: memoria_sabotaggio_zona_1
        name: "Memoria Sabotaggio Zona 1"
      - id: disinserita_area_1
        name: "Disinserita Area 1"